
#!/bin/bash

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║         🚀 ENVIANDO CÓDIGO PARA O GITHUB 🚀                  ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 Repositório: https://github.com/sistemabeleza/Code-Sistema-Beleza"
echo ""
echo "🔐 O GitHub vai pedir suas credenciais:"
echo "   • Username: seu-usuario-github"
echo "   • Password: Personal Access Token (não a senha normal!)"
echo ""
echo "❓ Não tem token? Crie em: https://github.com/settings/tokens"
echo "   (Marque a opção 'repo' ao criar o token)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📤 Iniciando upload..."
echo ""

git push -u origin master

if [ $? -eq 0 ]; then
    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                                                              ║"
    echo "║              ✅ SUCESSO! CÓDIGO NO GITHUB! ✅                ║"
    echo "║                                                              ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    echo "🌐 Acesse seu repositório:"
    echo "   https://github.com/sistemabeleza/Code-Sistema-Beleza"
    echo ""
    echo "📊 Total de arquivos enviados: 167"
    echo "📦 Total de commits: $(git log --oneline | wc -l)"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "✨ Próximos passos:"
    echo "   1. ✅ Código no GitHub - FEITO!"
    echo "   2. 🚀 Começar comercialização"
    echo "   3. 💰 Vender para os primeiros clientes"
    echo ""
else
    echo ""
    echo "❌ Erro ao enviar para o GitHub"
    echo ""
    echo "💡 Possíveis causas:"
    echo "   • Credenciais incorretas"
    echo "   • Token sem permissões de 'repo'"
    echo "   • Problemas de conexão"
    echo ""
    echo "🔧 Soluções:"
    echo "   1. Verifique seu token: https://github.com/settings/tokens"
    echo "   2. Crie um novo token se necessário"
    echo "   3. Tente novamente: ./push-github.sh"
    echo ""
fi
